services:
  web01:
    build:
      context: ./
      dockerfile: site1/Dockerfile
    image: web01
    container_name: web01
    networks:
      - asa-network
  web02:
    build:
      context: ./
      dockerfile: site2/Dockerfile
    image: web02
    container_name: web02
    networks:
      - asa-network
  web03:
    build:
      context: ./
      dockerfile: site3/Dockerfile
    image: web03
    container_name: web03
    networks:
      - asa-network
  proxy:
    build:
      context: ./
      dockerfile: proxy/Dockerfile
    image: proxy
    container_name: proxy
    ports:
      - "8080:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      - asa-network
  dns:
    build: ./dns
    image: dns
    container_name: ns1
    restart: always
    tty: true
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/primary:/etc/bind
    networks:
      - asa-network
  email:
    build: ./email
    image: email
    container_name: email
    ports:
      - "25:25/tcp"
      - "110:110/tcp"
      - "143:143/tcp"
      - "587:587/tcp"
      - "993:993/tcp"
      - "995:995/tcp"
    networks:
      - asa-network

#Docker Networks
networks:
  asa-network:
    driver: bridge
  